Repository viljamis/feature.js, pull requests merged in 2019-05, with the labels that each got.

#60 Fix possible bug with localStorage test
  feature.js
Labels: bug

#37 Escape dots in regex
  feature.js
Labels: bug

#56 Add ESLint
  .editorconfig
  .eslintignore
  .eslintrc.js
  .gitignore
  Gulpfile.js
  README.md
  feature.js
  package.json
Labels: housekeeping

#59 Allow Extensions
  .eslintrc.js
  Gulpfile.js
  README.md
  feature.js
  feature.test.js
  jest.config.js
  package.json
Labels: feature

#65 Add traditional CHANGELOG
  CHANGELOG.md
  README.md
Labels: housekeeping

#63 Be more pessimistic about the presence of window.navigator
  feature.js
Labels: bug
